In [1]:
import numpy as np

In [2]:
# Matrix der richtigen Größe mit Einsen
M = np.ones(shape=(10,10), dtype=np.int8) * -1
M

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]], dtype=int8)

In [3]:
# Matrix M mit den Vorgabewerten aus dem Mosaik-Rätsel füllen
M = np.array([[ 1, -1, -1,  6, -1,  3, -1, -1, -1, -1],
              [-1, -1, -1, -1, -1, -1, -1,  0, -1,  0],
              [ 4, -1,  8, -1,  9,  7, -1, -1, -1,  1],
              [-1, -1, -1,  8, -1, -1,  7, -1, -1,  3],
              [ 3, -1,  9, -1,  9, -1, -1,  9, -1, -1],
              [ 3, -1,  9, -1, -1, -1, -1, -1, -1, -1],
              [-1, -1, -1,  9, -1, -1,  9,  8, -1,  2],
              [-1, -1, -1,  6, -1, -1, -1, -1, -1, -1],
              [ 0, -1, -1, -1, -1, -1, -1, -1, -1,  0],
              [-1, -1,  0, -1, -1,  3, -1,  0, -1, -1]], dtype=np.int8)
M

array([[ 1, -1, -1,  6, -1,  3, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1,  0, -1,  0],
       [ 4, -1,  8, -1,  9,  7, -1, -1, -1,  1],
       [-1, -1, -1,  8, -1, -1,  7, -1, -1,  3],
       [ 3, -1,  9, -1,  9, -1, -1,  9, -1, -1],
       [ 3, -1,  9, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1,  9, -1, -1,  9,  8, -1,  2],
       [-1, -1, -1,  6, -1, -1, -1, -1, -1, -1],
       [ 0, -1, -1, -1, -1, -1, -1, -1, -1,  0],
       [-1, -1,  0, -1, -1,  3, -1,  0, -1, -1]], dtype=int8)

In [4]:
# Lösung mittels Gleichungssystem Ax = b.
# Der Vektor x enthält die Unbekannten x00, x01, ..., x10, x11, ..., xnm,
# wobei der erste Index die Zeile des Mosaiks beschreibt und der zweite die Spalte.
# Mögliche Lösungen für die Unbekannten x sind 1 oder 0.

In [5]:
# Vektor der rechten Seite B: Die vorgegebenen Zahlen im Mosaik 
B = []
x = np.nditer(M, flags=['multi_index'])
while not x.finished:
    if x[0] != -1:
        B.append(x[0])
    x.iternext()
B = np.asarray(B)
B

array([1, 6, 3, 0, 0, 4, 8, 9, 7, 1, 8, 7, 3, 3, 9, 9, 9, 3, 9, 9, 9, 8,
       2, 6, 0, 0, 0, 3, 0], dtype=int8)

In [6]:
# Koeffizientenmatrix A
A = np.zeros(shape=(B.size, M.size), dtype=np.int8)
A[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [7]:
x = np.nditer(M, flags=['c_index', 'multi_index'])

count = 0
while not x.finished:
    if x[0] != -1:
        print(x[0], "-", x.index, "-", x.multi_index)
        
        # Eigene Zeile
        A[count][x.index] = 1
        # Falls nicht die erste Spalte
        if x.multi_index[1] > 0:
            A[count][x.index - 1] = 1
        # Falls nicht die letzte Spalte
        if x.multi_index[1] < 9:
            A[count][x.index + 1] = 1
        
        # Falls nicht die erste Zeile
        if x.multi_index[0] > 0:
            A[count][x.index - 9] = 1
            # Falls nicht die erste Spalte
            if x.multi_index[1] > 0:
                A[count][x.index - 9 - 1] = 1
            # Falls nicht die letzte Spalte
            if x.multi_index[1] < 9:
                A[count][x.index - 9 + 1] = 1
        
        # Falls nicht die letzte Zeile
        if x.multi_index[0] < 9:
            A[count][x.index + 9] = 1
            # Falls nicht die erste Spalte
            if x.multi_index[1] > 0:
                A[count][x.index - 1] = 1
            # Falls nicht die letzte Spalte
            if x.multi_index[1] < 9:
                A[count][x.index + 1] = 1
        
        count += 1
    x.iternext()

1 - 0 - (0, 0)
6 - 3 - (0, 3)
3 - 5 - (0, 5)
0 - 17 - (1, 7)
0 - 19 - (1, 9)
4 - 20 - (2, 0)
8 - 22 - (2, 2)
9 - 24 - (2, 4)
7 - 25 - (2, 5)
1 - 29 - (2, 9)
8 - 33 - (3, 3)
7 - 36 - (3, 6)
3 - 39 - (3, 9)
3 - 40 - (4, 0)
9 - 42 - (4, 2)
9 - 44 - (4, 4)
9 - 47 - (4, 7)
3 - 50 - (5, 0)
9 - 52 - (5, 2)
9 - 63 - (6, 3)
9 - 66 - (6, 6)
8 - 67 - (6, 7)
2 - 69 - (6, 9)
6 - 73 - (7, 3)
0 - 80 - (8, 0)
0 - 89 - (8, 9)
0 - 92 - (9, 2)
3 - 95 - (9, 5)
0 - 97 - (9, 7)


In [9]:
A

array([[1, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 0]], dtype=int8)