In [28]:
# Spielfeld aus Datei auslesen und in Problem-Matrix schreiben
import numpy as np

gamefile = open('/home/alex/Schreibtisch/Raetsel/6x6.txt', 'r')
Prob = []
for line in gamefile:
    row = line.split()
    row = [k.replace('-', '-1') for k in row]
    row = [int(i) for i in row]
    Prob.append(row)
gamefile.close()

Prob = np.asarray(Prob)

In [29]:
print(Prob)

def matrix_ausgeben(Matrix):
    for row in Matrix:
        line = [str(e) for e in row]
        line = [e.replace('-1', '-') for e in line]
        line = ' '.join(str(e) for e in line)
        print(line)

matrix_ausgeben(Prob)
print(chr(9608))

[[ 1  1 -1  2 -1  2]
 [-1 -1 -1 -1  3 -1]
 [-1 -1  5 -1  4 -1]
 [ 3  4 -1  5 -1  3]
 [ 3 -1 -1  3 -1 -1]
 [-1 -1  2 -1  1 -1]]
1 1 - 2 - 2
- - - - 3 -
- - 5 - 4 -
3 4 - 5 - 3
3 - - 3 - -
- - 2 - 1 -
█


In [2]:
# Problem- und Resolution-Matrix anzeigen
print(Prob)
print()
print(Reso)

[[ 1 -1 -1  6 -1  3 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1  0 -1  0]
 [ 4 -1  8 -1  9  7 -1 -1 -1  1]
 [-1 -1 -1  8 -1 -1  7 -1 -1  3]
 [ 3 -1  9 -1  9 -1 -1  9 -1 -1]
 [ 3 -1  9 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1  9 -1 -1  9  8 -1  2]
 [-1 -1 -1  6 -1 -1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1 -1 -1 -1 -1  0]
 [-1 -1  0 -1 -1  3 -1  0 -1 -1]]

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [3]:
# Solver
def normieren():
    Reso[Reso > 0] = 1
    Reso[Reso < 0] = -1

for iter in range(100):
    for idx, targ in enumerate(Targ):
        # Prüfen, ob Umfeld durch einzelenen Vorgabewert definiert ist
        if Aff[idx].sum() == targ:
            print('Umfeld durch einzelnen Vorgabewert definert: ', Coord[idx])
            Reso += Aff[idx]
        normieren()
        # Im Umfeld einer 0 alles streichen
        if targ == 0:
            print('Umfeld von 0 alles gestrichen: ', Coord[idx])
            if Aff[idx].sum() > 0:
                Aff[idx] = -Aff[idx]
            Reso += Aff[idx]
        normieren()
        # Prüfen, ob im Umfeld einer Zahl bereits die richtige Anzahl an Kästchen ausgemalt ist, den Rest streichen
        AR = Aff[idx] * Reso
        AR[AR<0] = 0
        if AR.sum() == targ:
            print('Richtige Anzahl bereits ausgemalt, Rest gestrichen: ', Coord[idx])
            Reso += AR - Aff[idx]
        normieren()
        # Prüfen, ob im Umfeld einer Zahl bereits die richtige Anzahl an Kästchen gestrichen ist, den Rest ausmalen
        AR = Aff[idx] * Reso
        AR[AR>0] = 0
        if AR.sum() == (targ - Aff[idx].sum()):
            print('Richtige Anzahl bereits gestrichen, Rest ausgemalt: ', Coord[idx])
            Reso += AR + Aff[idx]
        normieren()
    if 0 not in Reso:
        print('Gelöst nach ',iter,'Iterationen.')
        break
    

# Problem- und Resolution-Matrix anzeigen
print(Prob)
print()
print(Reso)

Umfeld durch einzelnen Vorgabewert definert:  [0, 3]
Richtige Anzahl bereits ausgemalt, Rest gestrichen:  [0, 3]
Richtige Anzahl bereits gestrichen, Rest ausgemalt:  [0, 3]
Umfeld von 0 alles gestrichen:  [1, 7]
Umfeld von 0 alles gestrichen:  [1, 9]
Umfeld durch einzelnen Vorgabewert definert:  [2, 4]
Richtige Anzahl bereits ausgemalt, Rest gestrichen:  [2, 4]
Richtige Anzahl bereits gestrichen, Rest ausgemalt:  [2, 4]
Richtige Anzahl bereits gestrichen, Rest ausgemalt:  [2, 5]
Richtige Anzahl bereits gestrichen, Rest ausgemalt:  [3, 6]
Umfeld durch einzelnen Vorgabewert definert:  [4, 2]
Richtige Anzahl bereits ausgemalt, Rest gestrichen:  [4, 2]
Richtige Anzahl bereits gestrichen, Rest ausgemalt:  [4, 2]
Umfeld durch einzelnen Vorgabewert definert:  [4, 4]
Richtige Anzahl bereits ausgemalt, Rest gestrichen:  [4, 4]
Richtige Anzahl bereits gestrichen, Rest ausgemalt:  [4, 4]
Umfeld durch einzelnen Vorgabewert definert:  [4, 7]
Richtige Anzahl bereits ausgemalt, Rest gestrichen:  [4, 