In [2]:
import numpy as np

In [3]:
A = np.ones(shape=(10,10), dtype=np.int16) * -1
A

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]], dtype=int16)

In [9]:
A = np.array([[ 1, -1, -1,  6, -1,  3, -1, -1, -1, -1],
              [-1, -1, -1, -1, -1, -1, -1,  0, -1,  0],
              [ 4, -1,  8, -1,  9,  7, -1, -1, -1,  1],
              [-1, -1, -1,  8, -1, -1,  7, -1, -1,  3],
              [ 3, -1,  9, -1,  9, -1, -1,  9, -1, -1],
              [ 3, -1,  9, -1, -1, -1, -1, -1, -1, -1],
              [-1, -1, -1,  9, -1, -1,  9,  8, -1,  2],
              [-1, -1, -1,  6, -1, -1, -1, -1, -1, -1],
              [ 0, -1, -1, -1, -1, -1, -1, -1, -1,  0],
              [-1, -1,  0, -1, -1,  3, -1,  0, -1, -1]], dtype=np.int16)
index = 0
for rowidx, row in enumerate(A):
    for colidx, targ in enumerate(row):
        if targ != -1:
            print(index, "-", targ, "-", rowidx, colidx)
            index += 1

0 - 1 - 0 0
1 - 6 - 0 3
2 - 3 - 0 5
3 - 0 - 1 7
4 - 0 - 1 9
5 - 4 - 2 0
6 - 8 - 2 2
7 - 9 - 2 4
8 - 7 - 2 5
9 - 1 - 2 9
10 - 8 - 3 3
11 - 7 - 3 6
12 - 3 - 3 9
13 - 3 - 4 0
14 - 9 - 4 2
15 - 9 - 4 4
16 - 9 - 4 7
17 - 3 - 5 0
18 - 9 - 5 2
19 - 9 - 6 3
20 - 9 - 6 6
21 - 8 - 6 7
22 - 2 - 6 9
23 - 6 - 7 3
24 - 0 - 8 0
25 - 0 - 8 9
26 - 0 - 9 2
27 - 3 - 9 5
28 - 0 - 9 7


In [16]:
B = np.zeros(shape=(10,10), dtype=np.int16)
B

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int16)

In [36]:
x = np.nditer(A, flags=['multi_index'])
print(A)
while not x.finished:
    if x.multi_index[0] == 0:
        zA = 0
    else:
        zA = x.multi_index[0] - 1
    if x.multi_index[0] == 9:
        zE = 9
    else:
        zE = x.multi_index[0] + 1
    
    if x.multi_index[1] == 0:
        sA = 0
    else:
        sA = x.multi_index[1] - 1
    if x.multi_index[1] == 9:
        sE = 9
    else:
        sE = x.multi_index[1] + 1    
        
    A_Umfeld = A[zA:zE+1, sA:sE+1] 
    print(x[0])
    print(A_Umfeld)
    print(np.sum(A_Umfeld))
    x.iternext()

[[ 1 -1 -1  6 -1  3 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1  0 -1  0]
 [ 4 -1  8 -1  9  7 -1 -1 -1  1]
 [-1 -1 -1  8 -1 -1  7 -1 -1  3]
 [ 3 -1  9 -1  9 -1 -1  9 -1 -1]
 [ 3 -1  9 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1  9 -1 -1  9  8 -1  2]
 [-1 -1 -1  6 -1 -1 -1 -1 -1 -1]
 [ 0 -1 -1 -1 -1 -1 -1 -1 -1  0]
 [-1 -1  0 -1 -1  3 -1  0 -1 -1]]
1
[[ 1 -1]
 [-1 -1]]
-2
-1
[[ 1 -1 -1]
 [-1 -1 -1]]
-4
-1
[[-1 -1  6]
 [-1 -1 -1]]
1
6
[[-1  6 -1]
 [-1 -1 -1]]
1
-1
[[ 6 -1  3]
 [-1 -1 -1]]
5
3
[[-1  3 -1]
 [-1 -1 -1]]
-2
-1
[[ 3 -1 -1]
 [-1 -1  0]]
-1
-1
[[-1 -1 -1]
 [-1  0 -1]]
-5
-1
[[-1 -1 -1]
 [ 0 -1  0]]
-4
-1
[[-1 -1]
 [-1  0]]
-3
-1
[[ 1 -1]
 [-1 -1]
 [ 4 -1]]
1
-1
[[ 1 -1 -1]
 [-1 -1 -1]
 [ 4 -1  8]]
7
-1
[[-1 -1  6]
 [-1 -1 -1]
 [-1  8 -1]]
7
-1
[[-1  6 -1]
 [-1 -1 -1]
 [ 8 -1  9]]
17
-1
[[ 6 -1  3]
 [-1 -1 -1]
 [-1  9  7]]
20
-1
[[-1  3 -1]
 [-1 -1 -1]
 [ 9  7 -1]]
13
-1
[[ 3 -1 -1]
 [-1 -1  0]
 [ 7 -1 -1]]
4
0
[[-1 -1 -1]
 [-1  0 -1]
 [-1 -1 -1]]
-8
-1
[[-1 -1 -1]
 [ 0 -1  0]
 [-1 -1  1]]
-5
0
[[

In [1]:
A

NameError: name 'A' is not defined